---
title: "Analysis v1"
---

## Setup

```{r}

library(tidyverse)
library(janitor)
library(readxl)
library(lubridate)
```

## Import

Read in all the cleaned data from cities/counties. 

```{r}
amarillo <- read_csv("data-processed/Amarillo-City.csv")
carson <- read_csv("data-processed/Carson-County.csv")
howard <- read_csv("data-processed/Howard-County.csv")
midland <- read_csv("data-processed/Midland-City.csv")
lubbock <- read_csv("data-processed/Lubbock-County.csv")
monahans <- read_csv("data-processed/Monahans-City.csv")
moore <- read_csv("data-processed/Moore-County.csv")
nolan <- read_csv("data-processed/Nolan-County.csv")
odessa <- read_csv("data-processed/Odessa-City.csv")
pecos <- read_csv("data-processed/Pecos-City.csv")
plainview <- read_csv("data-processed/Plainview-City.csv")
randall <- read_csv("data-processed/Randall-County.csv")
slaton <- read_csv("data-processed/Slaton-City.csv")
snyder <- read_csv("data-processed/Snyder-City.csv")
wheeler <- read_csv("data-processed/Wheeler-County.csv")

```

## Nolan County

```{r}
nolan_age <- nolan |> group_by(age) |> 
  summarize(appearances = n()) |> 
  arrange(desc(appearances))

nolan_age

nolan_sex <- nolan |> group_by(sex) |> 
  summarize(appearances = n())

nolan_sex

nolan_race <- nolan |> group_by(race) |> 
  summarize(appearances = n())

nolan_race

```

## Plainview City

```{r}
plainview_age <- plainview |> group_by(age) |> 
  summarize(appearances = n()) |> 
  arrange(desc(appearances))
plainview_age

plainview_sex <- plainview |> group_by(sex) |> 
  summarize(appearances = n())
plainview_sex

plainview_race <- plainview |> group_by(race) |> 
  summarize(appearances = n())
plainview_race

```

## Slaton City

```{r}
slaton_sex <- slaton |> group_by(sex) |> 
  summarize(appearances = n())
slaton_sex

slaton_race <- slaton |> group_by(race) |> 
  summarize(appearances = n())
slaton_race
  
```

## Carson County

```{r}
carson_age <- carson |> group_by(age) |> 
  summarize(appearances = n()) |> 
  arrange(desc(appearances))
carson_age

carson_sex <- carson |> group_by(sex) |> 
  summarize(appearances = n())
carson_sex

carson_race <- carson |> group_by(race) |> 
  summarize(appearances = n())
carson_race

```

## Howard County

```{r}
howard_age <- howard |> group_by(age) |> 
  summarize(appearances = n()) |> 
  arrange(desc(appearances))
howard_age

howard_sex <- howard |> group_by(sex) |> 
  summarize(appearances = n())
howard_sex

```

## Midland City

```{r}
midland_age <- midland |> group_by(age) |> 
  summarize(appearances = n()) |> 
  arrange(desc(appearances))
midland_age

midland_sex <- midland |> group_by(sex) |> 
  summarize(appearances = n())
midland_sex

midland_race <- midland |> group_by(race) |> 
  summarize(appearances = n())
midland_race
```

## Monahans City

```{r}
monahans_age <- monahans |> group_by(age) |> 
  summarize(appearances = n()) |> 
  arrange(desc(appearances))
monahans_age

monahans_sex <- monahans |> group_by(sex) |> 
  summarize(appearances = n())
monahans_sex

monahans_race <- monahans |> group_by(race) |> 
  summarize(appearances = n())
monahans_race
```

## Moore County

```{r}

moore_sex <- moore |> group_by(sex) |> 
  summarize(appearances = n())
moore_sex

moore_race <- moore |> group_by(race) |> 
  summarize(appearances = n())
moore_race
```

## Randall County

```{r}
randall_age <- randall |> group_by(age) |> 
  summarize(appearances = n()) |> 
  arrange(desc(appearances))
randall_age

randall_sex <- randall |> group_by(sex) |> 
  summarize(appearances = n())
randall_sex

randall_race <- randall |> group_by(race) |> 
  summarize(appearances = n())
randall_race
```

## Odessa City

```{r}
odessa_race <- odessa |> group_by(race) |> 
  summarize(appearances = n()) |> 
  arrange(desc(appearances))
odessa_race

odessa_sex <- odessa |> group_by(sex) |> 
  summarize(appearances = n())
odessa_sex

odessa_ethnicity <- odessa |> group_by(ethnicity) |> 
  summarize(appearances = n())
odessa_ethnicity
```

