project:
  type: website
  output-dir: docs

website:
  title: "Marijuana Data Analysis"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - 01-Cleaning-AmarilloCity.qmd
      - 02-Cleaning-Carson-County.qmd
      - 03-Cleaning-Howard.qmd
      - 04-Cleaning-MidlandCity.qmd
      - 05-Cleaning-Lubbock-County.qmd
      - 06-Cleaning-MonahansCity.qmd
      - 07-Cleaning-MooreCounty.qmd
      - 08-Cleaning-NolanCounty.qmd
      - 09-Cleaning-OdessaCity.qmd
      - 10-Cleaning-PecosCity.qmd
      - 11-Cleaning-PlainviewCity.qmd
      - 12-Cleaning-RandallCounty.qmd
      - 13-Cleaning-SlatonCity.qmd
      - 14-Cleaning-SnyderCity.qmd
      - 15-Cleaning-WheelerCounty.qmd
      - 16-analysis-1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


df-print: paged
